[MERGE #2388 @meg-gupta] fix legacy builds
Merge pull request #2388 from meg-gupta:fixlegacy

Fix build errors raised in legacy builds. Majority of the changes are related to "error C2899:  typename cannot be used outside a template declaration" due to declaration with type FieldWithBarrier outside template. This is an error with older compilers.